# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
	ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Lane for distribution"
  lane :distribute do
      gradle(task: "clean assembleRelease")
      gradle(
          task: "assemble",
      )
  	firebase_app_distribution(
  		app: "1:152814340752:android:d334473d644773a287a615",
  		debug: true
  	)
  end

  lane :slack_build do
    gradle(task: "clean assembleRelease")
    gradle(
          task: "assemble",
    )
  	firebase_app_distribution(
  		app: "1:152814340752:android:d334473d644773a287a615",
  		testers: "bora5242@gmail.com, dltpdnjs2000@gmail.com, hobby0519@gmail.com, qnfn120@gmail.com, jow55255@gmail.com, imi21123@gmail.com, qnfn120@gmail.com",
  		debug: true
  	)

  	latest_release = firebase_app_distribution_get_latest_release(
        app: "1:152814340752:android:d334473d644773a287a615",
        debug: true
    )

    slack(
      		message: "successful deploy :rocket: link for app is : " + latest_release[:testingUri]
    )
  end

  # Add this to your Fastfile

  	error do |lane, exception|
  		slack(
  			message: exception.message,
  			success:false
  		)
  	end
end
