name: update
on: push
 
jobs:
  update:
    name: Fastlane Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - run: bundle install
   
      # - name: Run tests
      #   run: bundle exec fastlane test
  
      # - name: Run slack_build
      #   run: bundle exec fastlane slack_build