name: update
on: push
 
jobs:
  deploy:
    name: Fastlane Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
   
      - name: Run tests
        run: bundle exec fastlane test
  
      - name: Run slack_build
        run: bundle exec fastlane slack_build